# Generated by Django 4.2.1 on 2023-05-07 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('attack', models.PositiveSmallIntegerField(default=10)),
                ('defense', models.PositiveSmallIntegerField(default=10)),
                ('health', models.PositiveSmallIntegerField(default=10)),
                ('mana', models.PositiveSmallIntegerField(default=10)),
                ('spiritual_energy', models.PositiveSmallIntegerField(default=10)),
                ('actual_health', models.PositiveIntegerField(default=100)),
                ('actual_mana', models.PositiveIntegerField(default=10)),
                ('actual_spiritual_energy', models.PositiveIntegerField(default=10)),
                ('hp_update', models.DateTimeField(auto_now_add=True)),
                ('mana_update', models.DateTimeField(auto_now_add=True)),
                ('spiritual_energy_update', models.DateTimeField(auto_now_add=True)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('agility', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('bank_account', models.FloatField(default=5000)),
                ('player_account', models.FloatField(default=10000)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Players',
                'ordering': ('-nickname',),
            },
        ),
    ]
